org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.4
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

enable_example=true

mod_id=forgeattachment
mod_name=ForgeAttachment
mod_license=MIT
mod_version=0.0.1
mod_build_number=0
mod_group_id=io.zershyan
mod_authors=Zershyan
mod_description=Port of the NeoForge 1.21.1 data attachment system to Forge 1.20.1
mod_credits=
mod_url=